/*
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.semanticadaptation.tests

import be.uantwerpen.ansymo.semanticadaptation.semanticAdaptation.SemanticAdaptation
import com.google.inject.Inject
import org.junit.runner.RunWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.util.ParseHelper

@RunWith(XtextRunner)
@InjectWith(SemanticAdaptationInjectorProvider)
abstract class AbstractSemanticAdaptationParserTest extends AbstractSemanticAdaptationTest {

	@Inject extension ParseHelper<SemanticAdaptation>
	
	/**
	 * parses from an input file
	 */
	def SemanticAdaptation parseInputFile(String filename) {
		return readFile('input/'+filename).parse()
	}

}
