/*
 * generated by Xtext 2.10.0
 */
package be.uantwerpen.ansymo.semanticadaptation.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.util.IAcceptor
import org.eclipse.xtext.xbase.testing.CompilationTestHelper
import org.junit.Test
import org.junit.runner.RunWith
import org.eclipse.xtext.xbase.testing.CompilationTestHelper.Result

@RunWith(XtextRunner)
@InjectWith(SemanticAdaptationInjectorProvider)
class SemanticAdaptationGeneratorTest extends AbstractSemanticAdaptationTest{
	
	@Inject extension CompilationTestHelper
	
	@Test def window_SA() { __generate('input/power_window_case_study/window_sa.BASE.sa') }
	
	@Test def lazy_SA() { __generate('input/power_window_case_study/lazy.sa') }
	
	
	def void __generate(String filename) {
		//readFile(filename).assertCompilesTo('oracles/power_window_case_study/lazy.BASE.sa')
		
		readFile(filename).compile(new IAcceptor<CompilationTestHelper.Result>(){
			override accept(Result t) {
				// TODO: What kind of acceptance for generated text files? File comparison is very very brittle.
			}
		})
		
	}
}
