/*
 * generated by Xtext 2.11.0
 */
package be.uantwerpen.ansymo.semanticadaptation.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(SemanticAdaptationInjectorProvider)
class SemanticAdaptationParsingTest {
	
	@Test
	def void loadModel() {
		Assert.assertTrue(true)
	}
}
